# Generated by Django 2.2.6 on 2019-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0002_auto_20191202_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BooleanField(null=True),
        ),
    ]
