# Generated by Django 2.2.6 on 2019-12-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0003_auto_20191207_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_confirm',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
