# Generated by Django 2.2.6 on 2019-12-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0004_auto_20191207_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('abstract', models.TextField(blank=True, max_length=500, null=True)),
                ('ownerId', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_confirm',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
