# Generated by Django 2.2.6 on 2019-12-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0007_auto_20191208_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(choices=[('owner', 'owner'), ('manager', 'manager'), ('member', 'member')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='projectuser',
            name='roll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FocusApp.Rolls'),
        ),
    ]
