# Generated by Django 2.2.6 on 2020-01-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0008_auto_20191229_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filedname', models.TextField(blank=True, max_length=500, null=True)),
                ('fieldtype', models.TextField(blank=True, max_length=500, null=True)),
                ('fielddefaultvalue', models.TextField(blank=True, max_length=500, null=True)),
                ('fieldmondatory', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rolls',
            name='roll',
            field=models.CharField(choices=[('OWNER', 'owner'), ('MANAGER', 'manager'), ('MEMBER', 'member')], max_length=100),
        ),
    ]
