# Generated by Django 2.2.6 on 2020-01-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0009_auto_20200102_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='fielddefaultvalue',
        ),
        migrations.RemoveField(
            model_name='field',
            name='fieldmondatory',
        ),
        migrations.RemoveField(
            model_name='field',
            name='fieldtype',
        ),
        migrations.AddField(
            model_name='field',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FocusApp.Project'),
        ),
    ]
