# Generated by Django 2.2.6 on 2020-01-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0010_auto_20200102_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='filedname',
        ),
        migrations.AddField(
            model_name='field',
            name='fielddefaultvalue',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='fieldmondatory',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='fieldname',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='fieldtype',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
