# Generated by Django 2.2.6 on 2020-01-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0012_auto_20200107_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='have_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='table_name',
        ),
    ]
