# Generated by Django 2.2.6 on 2020-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0013_auto_20200107_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='have_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='table_name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
