# Generated by Django 2.2.6 on 2020-01-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0014_auto_20200107_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='have_table',
            field=models.BooleanField(default=False),
        ),
    ]
