# Generated by Django 2.2.6 on 2020-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0015_project_have_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
