# Generated by Django 2.2.6 on 2020-01-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0018_auto_20200112_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectuser',
            old_name='Project',
            new_name='project',
        ),
    ]
