# Generated by Django 2.2.6 on 2020-01-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0019_auto_20200112_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='have_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='have_table',
        ),
        migrations.RemoveField(
            model_name='project',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='field',
            name='fieldmondatory',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
