# Generated by Django 2.2.6 on 2020-01-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0020_auto_20200115_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='have_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='have_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='table_name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='fieldmondatory',
            field=models.BooleanField(default=False),
        ),
    ]
