# Generated by Django 2.2.6 on 2020-01-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusApp', '0021_auto_20200115_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolls',
            name='roll',
            field=models.CharField(choices=[('OWNER', 'owner'), ('MANAGER', 'manager'), ('MEMBER', 'member'), ('ADMIN', 'admin')], max_length=100),
        ),
    ]
